<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}
//Página que permite a criação/registo de aeroportos na base de dados
?>

<div class="cxfloataeroportoscreate">
    <div class="cardavioescreate">
        <ul class="firstline">
            <li class="textoAdicionarAviao">Adicionar Aeroporto</li>
            <a href="<?=Url::toRoute('airports/index')?>">
                <li class="veravioes">Ver Aeroportos</li>
            </a>
        </ul>
        <form class="formulario-todo" action="<?=Url::toRoute('airports/store')?>" method="post">
            <input type="text" class="form-control form" name="airportname" title="Insira um nome para o Aeroporto" placeholder="Nome do Aeroporto" required>
            <input type="text" class="form-control form" name="country" title="Insira o nome do País" placeholder="País" required>
            <input type="text" class="form-control form" name="city" title="Insira o nome da Cidade" placeholder="Cidade" required>
            <input class="btn botaosignin" type="submit" value="Adicionar">
        </form>
        </ul>
    </div>
</div>

<?=Layout::includeLayout('footer')?>