<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}
?>

$aeroporto = Data::get('aeroporto');
?>

    <div class="cxfloataeroportoscreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Aeroporto</li>
                <a href="<?=Url::toRoute('airports/index')?>">
                    <li class="veravioes">Ver Aeroportos</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('airports/update', $aeroporto[0]->airports_id)?>" method="post">
                <input type="text" class="form-control form" value="<?=$aeroporto[0]->airportname?>" name="airportname" title="Insira um nome para o Aeroporto" placeholder="Nome do Aeroporto" required>
                <input type="text" class="form-control form" value="<?=$aeroporto[0]->country?>" name="country" title="Insira o nome do País" placeholder="País" required>
                <input type="text" class="form-control form" value="<?=$aeroporto[0]->city?>" name="city" title="Insira o nome da Cidade" placeholder="Cidade" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>
<?=Layout::includeLayout('footer')?>


