<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}
?>

<?php $aeroportos = Data::get('airports');
$searchbar = Data::get('searchbar');
$aero = new Airport();
//Página que permite ver todos os aeroportos registados na base de dados
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao"><a href="<?=Url::toRoute('airports/index')?>">Aeroportos</a></li>
            <li>
                <form class="formSearch" method="post" action="<?=Url::toRoute('airports/search')?>">
                    <input type="text" class="form-control form" title="Escreva aqui o que quer procurar" placeholder="Procurar" name="search" value="<?=$searchbar?>" required>
                    <input type="submit" class="btn botaosearch" value="Procurar">
                </form>
            </li>
            <a href="<?=Url::toRoute('airports/create')?>">
                <li class="adicionaraviao">Adicionar Aeroporto</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Nome do Aeroporto</th>
                    <th scope="col"></th>
                    <th scope="col">País</th>
                    <th scope="col">Cidade</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($aeroportos as $dados){ ?>
                    <tr>
                        <td><?=$dados->airportname?></td>
                        <td><img src="<?=$dados->flag?>" width=30></td>
                        <td><?=$dados->country?></td>
                        <td><?=$dados->city?></td>
                        <td><a href="<?=Url::toRoute('airports/edit', $dados->airports_id)?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="30"></a></td>
                        <td><a href="<?=Url::toRoute('airports/destroy', $dados->airports_id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

            <!--Mensagem de nenhum avião encontrado-->
            <?=(empty($aeroportos))?'<p class="nenhumVoo">Nenhum aeroporto encontrado</p>':''?>

        </div>

        <!--Mensagem de erro ao tentar eliminar chaves estrangeiras-->
        <?=(isset($_SESSION['mensagemErro']))?'<p class="nenhumVoo">'.$_SESSION['mensagemErro'].'</p>':''?>
        <?php unset($_SESSION['mensagemErro']); ?>

    </div>
</div>

<?=Layout::includeLayout('footer')?>

