<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('header');

$escala = Data::get('escala');
?>

    <div class="cxfloatvooscreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Escala</li>
                <a href="<?=Url::toRoute('escalas/index')?>">
                    <li class="veravioes">Ver Escalas</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('escalas/update', $escala[0]->idvoo)?>" method="post">
                <input type="text" class="form-control form" value="<?=$escala[0]->nomevoo?>" name="NomeVoo" title="Insira o nome da escala" placeholder="Escala" required>
                <input type="datetime-local" class="form-control form" value="<?=date('Y-m-d',strtotime($escala[0]->datahorapartida))?>T<?=date('H:i',strtotime($escala[0]->datahorapartida))?>" name="DataHoraPartida" title="Insira a data de partida do voo" placeholder="Data de Partida" required>
                <input type="datetime-local" class="form-control form" value="<?=date('Y-m-d',strtotime($escala[0]->datahorachegada))?>T<?=date('H:i',strtotime($escala[0]->datahorachegada))?>" name="DataHoraChegada" title="Insira a data de chegada do voo" placeholder="Data de Chegada" required>
                <input type="text" class="form-control form" value="<?=$escala[0]->idaeroportoorigem?>" name="IdAeroportoOrigem" title="Insira o aeroporto de origem" placeholder="Aeroporto de Origem" required>
                <input type="text" class="form-control form" value="<?=$escala[0]->idaeroportodestino?>" name="IdAeroportoDestino" title="Insira o aeroporto de destino" placeholder="Aeroporto de Destino" required>
                <input type="text" class="form-control form" value="<?=$escala[0]->idaviao?>" name="IdAviao" title="Insira o avião" placeholder="Avião" required>
                <input type="text" class="form-control form" value="<?=$escala[0]->idvoo?>" name="IdVoo" title="Insira o voo" placeholder="Voo" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>