<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}
//Págian que permite a inserção de novos aviões
?>

<div class="cxfloatavioescreate">
    <div class="cardavioescreate">
        <ul class="firstline">
            <li class="textoAdicionarAviao">Adicionar Avião</li>
            <a href="<?=Url::toRoute('airplanes/index')?>">
                <li class="veravioes">Ver aviões</li>
            </a>
        </ul>
        <form class="formulario-todo" action="<?=Url::toRoute('airplanes/store')?>" method="post">
            <input type="text" class="form-control form" name="airplanereference" title="Insira a referência do avião" maxlength="100" placeholder="Referência" required>
            <input type="text" class="form-control form" name="airplanename" title="Insira um nome para o avião" maxlength="100" placeholder="Nome" required>
            <input type="text" class="form-control form" name="shippingcompany" title="Insira o nome da transportadora" maxlength="100" placeholder="Transportadora" required>
            <input type="number" class="form-control form" name="capacity" title="Insira a capacidade do avião" min="1" max="999" placeholder="Lotação Máxima" required>
            <input class="btn botaosignin" type="submit" value="Adicionar">
        </form>
        </ul>
    </div>
</div>

<?=Layout::includeLayout('footer')?>