<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}

$aviao = Data::get('airplane');
//Página que permite a edição de dados do aviao selecionado pelo user
?>

    <div class="cxfloatavioescreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Avião</li>
                <a href="<?=Url::toRoute('airplanes/index')?>">
                    <li class="veravioes">Ver aviões</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('airplanes/update', $aviao->airplanes_id)?>" method="post">
                <input type="text" class="form-control form" value="<?=$aviao->airplanereference?>" name="airplanereference" title="Insira a referência do avião" placeholder="Referência"  required>
                <input type="text" class="form-control form" value="<?=$aviao->airplanename?>" name="airplanename" title="Insira um nome para o avião" placeholder="Nome" required>
                <input type="text" class="form-control form" value="<?=$aviao->shippingcompany?>" name="shippingcompany" title="Insira o nome da transportadora" placeholder="Transportadora" required>
                <input min="1" type="number" class="form-control form" value="<?=$aviao->capacity?>" name="capacity" title="Insira a capacidade do avião" placeholder="Lotação Máxima" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>