<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

?>

<?php
switch ($_SESSION['tipoUser']) {
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}
?>

<?php $avioes = Data::get('airplanes');
?>

<div class="cxfloatavioes">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao">Aviões</li>
            <a href="<?=Url::toRoute('airplanes/create')?>">
                <li class="adicionaraviao">Adicionar avião</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Nome do avião</th>
                    <th scope="col">Transportadora</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($avioes as $dados){ ?>
                    <tr>
                        <td><?=$dados->airplanename?></td>
                        <td><?=$dados->shippingcompany?></td>
                        <td><a href="<?=Url::toRoute('airplanes/edit', $dados->airplanes_id)?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="30"></a></td>
                        <td><a href="<?=Url::toRoute('airplanes/destroy', $dados->airplanes_id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

