<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

?>

<?php
switch ($_SESSION['tipoUser']) {
    // Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}
?>

<?php $avioes = Data::get('airplanes');
$searchbar = Data::get('searchbar');
// Página que mostra todos os aviões registados na base de dados
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao"><a href="<?=Url::toRoute('airplanes/index')?>">Aviões</a></li>
            <li>
                <form class="formSearch" method="post" action="<?=Url::toRoute('airplanes/search')?>">
                    <input type="text" class="form-control form" title="Escreva aqui o que quer procurar" placeholder="Procurar" name="search" value="<?=$searchbar?>" required>
                    <input type="submit" class="btn botaosearch" value="Procurar">
                </form>
            </li>
            <a href="<?=Url::toRoute('airplanes/create')?>">
                <li class="adicionaraviao">Adicionar avião</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Referência do avião</th>
                    <th scope="col">Nome do avião</th>
                    <th scope="col">Transportadora</th>
                    <th scope="col">Lotação Máxima</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($avioes as $dados){ ?>
                    <tr>
                        <td><?=$dados->airplanereference?></td>
                        <td><?=$dados->airplanename?></td>
                        <td><?=$dados->shippingcompany?></td>
                        <td><?=$dados->capacity?></td>
                        <td><a href="<?=Url::toRoute('airplanes/edit', $dados->airplanes_id)?>" title="Editar"><?=imgeditar()?></a></td>
                        <td><a href="<?=Url::toRoute('airplanes/destroy', $dados->airplanes_id)?>" title="Apagar"><?=imgapagar()?></a></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>

            <!--Mensagem de nenhum avião encontrado-->
            <?=(empty($avioes))?'<p class="nenhumVoo">Nenhum avião encontrado</p>':''?>

        </div>

        <!--Mensagem de erro ao tentar eliminar chaves estrangeiras-->
        <?=(isset($_SESSION['mensagemErro']))?'<p class="nenhumVoo">'.$_SESSION['mensagemErro'].'</p>':''?>
        <?php unset($_SESSION['mensagemErro']); ?>

    </div>
</div>

<?=Layout::includeLayout('footer')?>

