<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('header');

$utilizador = Data::get('utilizador');
?>

    <div class="cxfloatavioescreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Utilizador</li>
                <a href="<?=Url::toRoute('avioes/index')?>">
                    <li class="veravioes">Ver aviões</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('avioes/update', $aviao[0]->idaviao)?>" method="post">
                <input type="text" class="form-control form" value="<?=$aviao[0]->nomeaviao?>" name="NomeAviao" title="Insira um nome para o avião" placeholder="Nome" required>
                <input type="text" class="form-control form" value="<?=$aviao[0]->transportadora?>" name="Transportadora" title="Insira o nome da transportadora" placeholder="Transportadora" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>