<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('header');

$utilizador = Data::get('utilizador');
?>

    <div class="cxfloatutilizadoredit">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Utilizador</li>
                <?php if($_SESSION['tipoUser'] == 'administrador'){ ?>
                    <a href="<?=Url::toRoute('utilizadores/showall')?>">
                        <li class="veravioes">Ver utilizadores</li>
                    </a>
                <?php }else{ ?>
                    <a href="<?=Url::toRoute('voos/index')?>">
                        <li class="veravioes">Voltar</li>
                    </a>
                <?php } ?>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('utilizadores/update', $utilizador[0]->idutilizador)?>" method="post">
                <input type="text" class="form-control form" value="<?=$utilizador[0]->nomecompleto?>" name="NomeCompleto" title="Insira o seu nome" placeholder="Nome" required>
                <input type="date" class="form-control form" value="<?=date('Y-m-d',strtotime($utilizador[0]->datanascimento))?>" name="DataNascimento" title="Insira a sua data de nascimento" required>
                <input type="email" class="form-control form" value="<?=$utilizador[0]->email?>" name="Email" title="Insira o seu email" placeholder="Email" required>
                <input type="number" class="form-control form" value="<?=$utilizador[0]->telefone?>" name="Telefone" title="Insira o seu telefone" placeholder="Telefone" required>
                <input type="text" class="form-control form" value="<?=$utilizador[0]->utilizador?>" name="Utilizador" title="Insira o seu nome de utilizador" placeholder="Username" required>
                <input type="password" class="form-control form" value="<?=$utilizador[0]->passwordutilizador?>" name="PasswordUtilizador" title="Insira a sua password" placeholder="Password" required>
                <input type="text" class="form-control form" value="<?=$utilizador[0]->nomecompleto?>" name="NomeCompleto" title="Insira o seu nome" placeholder="Nome" required>
                <?php if($_SESSION['tipoUser'] == 'administrador'){ ?>
                    <select class="form-control form">
                        <option value="administrador" <?=($utilizador[0]->perfil == "administrador")?'selected':''?>>administrador</option>
                        <option value="funcionario" <?=($utilizador[0]->perfil == "funcionario")?'selected':''?>>funcionario</option>
                        <option value="utilizador" <?=($utilizador[0]->perfil == "passageiro")?'selected':''?>>passageiro</option>
                    </select>
                <?php } ?>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>