<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('loginheader') ?>

    <div id="imagemlogin">
        <div class="cxfloat">
            <div class="cardtwo">
                <ul class="firstline">
                    <li class="textologin">LOGIN</li>
                    <a href="<?=Url::toRoute('utilizadores/create')?>">
                        <li class="createaccount">Criar conta</li>
                    </a>
                </ul>
                <form class="formulario-todo" method="post" action="<?=Url::toRoute('utilizadores/show', "passageiro")?>">
                    <input type="text" class="form-control form" name="Utilizador" title="Insira um username" placeholder="Username" required>
                    <input type="password" class="form-control form" name="PasswordUtilizador" title="Insira uma password" placeholder="Password" required>
                    <span id="mensagem"><?=(isset($_SERVER['mensagem']))?$_SERVER['mensagem']:""?></span>
                    <input class="btn botaosignin" type="submit" value="Entrar  ">
                </form>

                <ul class="Secondline">
                    <a href="#">
                    <li class="forgotpass">Esqueceu a sua password?</li>
                    </a>
                </ul>
            </div>
        </div>
    </div>