<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

?>

<?=Layout::includeLayout('header')?>

<?php $utilizadores = Data::get('utilizadores');
?>

<div class="cxfloatshowall">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao">Utilizadores</li>
            <a href="<?=Url::toRoute('utilizadores/create')?>">
                <li class="adicionaraviao">Adicionar Utilizador</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Data de nascimento</th>
                    <th scope="col">Email</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Utilizador</th>
                    <th scope="col">Password</th>
                    <th scope="col">Perfil</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($utilizadores as $dados){ ?>
                    <tr>
                        <td><?=$dados->nomecompleto?></td>
                        <td><?=date('d/m/Y', strtotime($dados->datanascimento))?></td>
                        <td><?=$dados->email?></td>
                        <td><?=$dados->telefone?></td>
                        <td><?=$dados->utilizador?></td>
                        <td><?=$dados->passwordutilizador?></td>
                        <td><?=$dados->perfil?></td>
                        <td><a href="<?=Url::toRoute('utilizadores/edit', $dados->id)?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="30"></a></td>
                        <td><a href="<?=Url::toRoute('utilizadores/destroy', $dados->id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>