<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('header');

$aeroporto = Data::get('aeroporto');
?>

    <div class="cxfloatavioescreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Aeroporto</li>
                <a href="<?=Url::toRoute('aeroportos/index')?>">
                    <li class="veravioes">Ver Aeroportos</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('aeroportos/update', $aeroporto[0]->idaeroporto)?>" method="post">
                <input type="text" class="form-control form" value="<?=$aeroporto[0]->nomeaeroporto?>" name="NomeAeroporto" title="Insira um nome para o Aeroporto" placeholder="Nome do Aeroporto" required>
                <input type="text" class="form-control form" value="<?=$aeroporto[0]->pais?>" name="Pais" title="Insira o nome do País" placeholder="País" required>
                <input type="text" class="form-control form" value="<?=$aeroporto[0]->cidade?>" name="Cidade" title="Insira o nome da Cidade" placeholder="Cidade" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>
<?=Layout::includeLayout('footer')?>


