<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\WebObjects\URL;
//Header de passageiro
//Com os respetivos botões para as páginas restritas ao utilizador passageiro
?>

<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author"      content="Silvio Priem Mendes, PhD">

    <title>Aeroporto</title>

    <?=AssetBundler::css()?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png')?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css')?>" media="screen" >

    <link rel="stylesheet" href="<?= Asset::css('/style.css')?>" media="screen">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js')?>"></script>
    <script src="<?= Asset::js('respond.min.js')?>"></script>
    <![endif]-->
</head>

<body style="background-image: url(<?=Asset::image('loginFundo'.rand(1,3).'.jpg')?>);" class="home">
<!-- Fixed navbar -->
<div style="background-color: rgba(26, 29, 34, 0.7)" class="navbar navbar-inverse navbar-fixed-top headroom" >
    <div class="container">
        <div class="navbar-header">
            <!-- Button for smallest screens -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a class="navbar-brand" href="<?= URL::toRoute('flights/index')?>">PASSAGEIRO</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li class="active"><a href="<?= URL::toRoute('flights/index')?>">Voos</a></li>
                <li><a href="<?= URL::toRoute('purchasesflights/show')?>">Passagens adquiridas</a></li>
                <li><a href="<?=URL::toRoute('users/edit', $_SESSION['userid'])?>">Perfil</a></li>
                <li><a class="btn" href="<?= URL::toRoute('users/sair')?>">Terminar Sessão</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>
<!-- /.navbar -->
<header id="head" class="secondary"></header>