<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    // Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}
?>

<?php
    $user = Data::get('user');
    $voo = Data::get('voo');
    $lugar = Data::get('lugar');
    $voosvolta = Data::get('voosvolta');
?>

<!--Importar funções JS-->
<script src="<?= Asset::js('script.js')?>"></script>

<div class="cxfloatvooscreate">
    <div class="cardavioescreate">
        <ul class="firstline">
            <li class="textoAdicionarAviao">Comprar Bilhete</li>
            <a href="<?=Url::toRoute('flights/user_search')?>">
                <li class="veravioes">Pesquisar Voos</li>
            </a>
        </ul>
        <div class="tabelaPlaceVoo">
            <form class="formulario-todo" action="<?=Url::toRoute('users_flights/store')?>" method="post">

                <select class="form-control form visaocompra" name="client_id" title="cliente">
                    <option class="optionvisaocompra" value="<?=$user->users_id?>"selected><span style="font-weight: bold">Cliente: </span><?=$user->fullname?></option>
                </select>

                <select class="form-control form visaocompra" name="flight_id" title="Voo">
                    <option class="optionvisaocompra" value="<?=$voo->flights_id?>"selected>Código do Voo: <?=$voo->flightname?></option>
                </select>

                <select class="form-control form visaocompra" name="flight_back_id" title="Voo de Volta">
                    <option class="form-control form" value="<?=(isset($voo->userflight)) ? $voo->userflight->flight_back_id : null?>"selected>Código do Voo de Volta: <?=(isset($voo->userflight)) ? $voo->userflight->flight_back_id : ''?></option>
                </select>

                <select class="form-control form visaocompra" name="price" title="Preço">
                    <option class="form-control form" value="<?= $voo->price?>"selected>Preço: <?=$voo->price ?>€</option>
                </select>

                <select class="form-control form visaocompra" name="planeplace" title="Lugar no avião">
                    <option class="form-control form" value="<?=$lugar?>"selected>Lugar no avião: <?=$lugar?></option>
                </select>

                <?php if($voosvolta != null){ ?>
                    <div class="checkcontainer">
                        <input id="checkbutton" type="checkbox" onclick="VooVolta()">
                        <label for="checkbutton">Comprar Voo de volta</label>
                    </div>
                <?php } ?>

                <select class="form-control form voovolta" title="Escolher voo de volta">
                    <?php foreach ($voosvolta as $dados){ ?>
                        <option class="form-control form" value="<?=$dados->flights_id?>"><?=date('d/m/Y H:i', strtotime($dados->datehourdeparture))?></option>
                    <?php } ?>
                </select>

                <input class="btn botaosignin" type="submit" value="Pagamento">

            </form>
        </div>
        </ul>
    </div>
</div>

<?=Layout::includeLayout('footer') ?>