<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    // Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}
?>

<?php
    $aeroportos = Data::get('airports');
    $avioes = Data::get('airplanes');
?>

<div class="cxfloatvooscreate">
    <div class="cardavioescreate">
        <ul class="firstline">
            <li class="textoAdicionarAviao">Comprar Bilhete</li>
            <a href="<?=Url::toRoute('users_flights/index')?>">
                <li class="veravioes">Ver Compras</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <form class="formulario-todo" action="<?=Url::toRoute('users_flights/store')?>" method="post">

                <input type="text" class="form-control form" name="flightname" title="clientID" placeholder="Nome do Voo" required>

                <input type="datetime-local" class="form-control form" name="datehourdeparture" title="Insira a data de partida do voo" placeholder="Data de Partida" required>

                <input type="datetime-local" class="form-control form" name="datehourarrival" title="Insira a data de chegada do voo"


                <input class="btn botaosignin" type="submit" value="Adicionar">

            </form>
        </div>
        </ul>
    </div>
</div>

<?=Layout::includeLayout('footer')?>