<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    // Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}
?>

<?php
    $userflight = Data::get('userflight');
?>

    <div class="cxfloatvooscreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Fazer Check-in</li>
            </ul>
            <div class="tabelaPlaceVoo">
                <form class="formulario-todo" action="<?=Url::toRoute('users_flights/update', $userflight->users_flights_id)?>" method="post">

                    <select class="form-control form visaocompra" name="client_id" title="cliente" readonly="true">
                        <option class="optionvisaocompra" value="<?=$userflight->client_id?>"selected><span style="font-weight: bold">Cliente: </span><?=$userflight->client_id?></option>
                    </select>

                    <select class="form-control form visaocompra" name="flight_id" title="Voo" readonly="true">
                        <option class="optionvisaocompra" value="<?=$userflight->flight_id?>"selected>Código do Voo: <?=$userflight->flight_id?></option>
                    </select>

                    <select class="form-control form visaocompra" name="flight_back_id" title="Voo de Volta" readonly="true">
                        <option class="form-control form" value="<?=(isset($userflight->flight_back_id)) ? $userflight->flight_back_id : null?>"selected>Código do Voo de Volta: <?=(isset($userflight->flight_back_id)) ? $userflight->flight_back_id : ''?></option>
                    </select>

                    <select class="form-control form visaocompra" name="price" title="Preço" readonly="true">
                        <option class="form-control form" value="<?= $userflight->price?>"selected>Preço: <?=$userflight->price ?>€</option>
                    </select>

                    <select class="form-control form visaocompra" name="planeplace" title="Lugar no avião" readonly="true">
                        <option class="form-control form" value="<?=$userflight->planeplace?>"selected>Lugar no avião: <?=$userflight->planeplace?></option>
                    </select>

                    <select class="form-control form" name="checkin" title="Lugar no avião">
                        <option class="form-control form" value="0" <?= ($userflight->checkin == 0) ? 'selected' : ''?>>Check-in: Pendente</option>
                        <option class="form-control form" value="1" <?= ($userflight->checkin == 1) ? 'selected' : ''?>>Check-in: Concluído</option>
                    </select>

                    <input class="btn botaosignin" type="submit" value="Pagamento">

                </form>
            </div>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer') ?>