<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    // Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}
?>

<?php $compras = Data::get('users_flights');
$searchbar = Data::get('searchbar');
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao"><a href="<?=Url::toRoute('users_flights/index')?>">Voos</a></li>
            <li>
                <form class="formSearch" method="post" action="<?=Url::toRoute('users_flights/search')?>">
                    <input type="text" class="form-control form" title="Escreva aqui o que quer procurar" placeholder="Procurar" name="search" value="<?=$searchbar?>" required>
                    <input type="submit" class="btn botaosearch" value="Procurar">
                </form>
            </li>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Voo</th>
                    <th scope="col">Voo de Volta</th>
                    <th scope="col">Passageiro</th>
                    <th scope="col">Data de Compra</th>
                    <th scope="col">Lugar no Avião</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Check-In</th>
                    <th scope="col"></th>

                    <!--Tirar a opção ao passageiro de poder alterar ou apagar as compras-->
                    <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    <?php } ?>

                </tr>
                </thead>
                <tbody>
                <?php foreach ($compras as $dados){ ?>
                    <tr>
                        <td><?=$dados->flight->flightname?></td>
                        <td><?=($dados->flight_back_id != null) ? $dados->flight_back->flightname : 'X' ?></td>
                        <td><?=$dados->client->fullname?></td>
                        <td><?=date('d/m/Y H:i',strtotime($dados->purchasedate))?></td>
                        <td><?=$dados->planeplace?></td>
                        <td><?=($dados->flight_back != null)?$dados->price+$dados->flight_back->price:$dados->price.'€'?></td>
                        <td><?=($dados->checkin == 0) ? 'Pendente' : 'Concluído'?></td>
                        <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                            <td><a href="<?=Url::toRoute('users_flights/edit', $dados->users_flights_id)?>"><img title="Fazer Check-in" alt="editar" src="<?=Asset::image('editar.png')?>" width="32"></a></td>
                            <td><a href="<?=Url::toRoute('users_flights/destroy', $dados->users_flights_id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                        <?php }else{ ?>
                            <td><a href="<?=Url::toRoute('users_flights/show', $dados->users_flights_id)?>"><img title="Exportar" alt="Exportar" src="<?=Asset::image('PDFExport.png')?>" width="32"></a></td>
                        <?php }?>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

