<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}
?>

<?php $compras = Data::get('users_flights');
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao">Compras</li>
            <a href="<?=Url::toRoute('flights/create')?>">
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">ID de cliente</th>
                    <th scope="col">ID do Voo</th>
                    <th scope="col">ID do Voo de Volta</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Data de Compra</th>
                    <th scope="col">Lugar no Avião</th>
                    <th scope="col">Check-In</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($compras as $dados){ ?>
                    <tr>
                        <td><?=$dados['client']?></td>
                        <td><?=$dados['flight']?></td>
                        <td><?=$dados['flight_back']?></td>
                        <td><?=$dados['price']?></td>
                        <td><?=$dados['purchasedate']?></td>
                        <td><?=$dados['planeplace']?></td>
                        <td><?=$dados['checkin']?></td>
                        <td><a href="<?=Url::toRoute('users_flights/edit', $dados['id'])?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="30"></a></td>
                        <td><a href="<?=Url::toRoute('users_flights/destroy', $dados['id'])?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

