<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    // Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}
?>

<?php $compras = Data::get('users_flights');
$searchbar = Data::get('searchbar');
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao"><a href="<?=Url::toRoute('users_flights/index')?>">Voos</a></li>
            <li>
                <form class="formSearch" method="post" action="<?=Url::toRoute('users_flights/search')?>">
                    <input type="text" class="form-control form" title="Escreva aqui o que quer procurar" placeholder="Procurar" name="search" value="<?=$searchbar?>" required>
                    <input type="submit" class="btn botaosearch" value="Procurar">
                </form>
            </li>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Voo</th>
                    <th scope="col">Voo de Volta</th>
                    <th scope="col">Passageiro</th>
                    <th scope="col">Data de Compra</th>
                    <th scope="col">Lugar no Avião</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Check-In</th>
                    <th scope="col"></th>

                    <!--Tirar a opção ao passageiro de poder alterar ou apagar as compras-->
                    <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    <?php } ?>

                </tr>
                </thead>
                <tbody>
                <?php foreach ($compras as $dados){ ?>
                    <tr>
                        <td><?=$dados->flight->flightname?></td>
                        <td><?=($dados->flight_back_id != null) ? $dados->flight_back->flightname : 'X' ?></td>
                        <td><?=$dados->client->fullname?></td>
                        <td><?=date('d/m/Y H:i',strtotime($dados->purchasedate))?></td>
                        <td><?=$dados->planeplace?></td>
                        <td><?=($dados->flight_back != null)?$dados->price+$dados->flight_back->price:$dados->price.'€'?></td>
                        <td><?=($dados->checkin == 0) ? 'Pendente' : 'Concluído'?></td>
                        <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                            <td><a title="Ver detalhes do voo" href="<?=Url::toRoute('users_flights/showflight', $dados->users_flights_id)?>">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="black" class="bi bi-card-list" viewBox="0 0 16 16">
                                        <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                                        <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zM4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                                    </svg>
                                </a></td>
                            <td><a title="Fazer Check-in" href="<?=Url::toRoute('users_flights/edit', $dados->users_flights_id)?>">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="black" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                    </svg>
                                </a></td>
                            <td><a title="Apagar" href="<?=Url::toRoute('users_flights/destroy', $dados->users_flights_id)?>">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="black" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                    </svg>
                                </a></td>
                        <?php }else{ ?>
                            <td><a title="Exportar" href="<?=Url::toRoute('users_flights/show', $dados->users_flights_id)?>"><?=imgimprimir()?></a></td>
                        <?php }?>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

