<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use Tracy\Dumper;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}
?>

<?php $compra = Data::get('compra');
//Dumper::dump($compra);
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao">Exportação da compra</li>
            <a href="<?=Url::toRoute('users_flights/index')?>">
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Voo</th>
                    <th scope="col">Voo de Volta</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Data de Compra</th>
                    <th scope="col">Lugar no Avião</th>
                    <th scope="col">Check-In</th>
                    <th scope="col"></th>

                    <!--Tirar a opção ao passageiro de poder alterar ou apagar as compras-->
                    <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    <?php } ?>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($compra as $dados){ ?>
                    <tr>
                        <td><?=$dados->flight?></td>
                        <td><?=$dados->flight_back?></td>
                        <td><?=$dados->price.'€'?></td>
                        <td><?=$dados->purchasedate?></td>
                        <td><?=$dados->planeplace?></td>
                        <td><?=$dados->checkin?></td>
                        <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                            <td><a href="<?=Url::toRoute('users_flights/edit', $dados->flights_id, $dados->$_SESSION[''])?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="32"></a></td>
                            <td><a href="<?=Url::toRoute('users_flights/destroy', $dados->users_flights_id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                        <?php }else{ ?>
                            <td><a href="<?=Url::toRoute('users_flights/show', $dados->user_flights_id)?>"><img title="Mostrar" alt="Detalhes" src="<?=Asset::image('comprar.png')?>" width="32"></a></td>
                        <?php }?>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

