<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use Tracy\Dumper;


switch ($_SESSION['tipoUser']) {
    // Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}
$compra = Data::get('compra');
ActiveRecord\Connection::$datetime_format = 'Y-m-d H:i:s';

// Include the main TCPDF library (search for installation path).
require_once '..\vendor\tecnickcom\tcpdf\examples\tcpdf_include.php';

// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Our Code World');
$pdf->SetTitle('Example Write Html');


// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// add a page
$pdf->AddPage();

//Verifar estado do checkin
if($compra->checkin == 0){
     $checkin = "Pendente";
}
else{
    $checkin = "Concluído";
}

$flightback = ($compra->flight_back_id != null) ?
    '<br><tr><td><b>Voo de Regresso:</b></td><td>'.$compra->flight_back->flightname.'</td></tr>
    <tr><td><b>Data de Regresso:</b></td><td>' .date('d/m/Y', strtotime($compra->flight_back->datehourdeparture)).'</td></tr>
    <tr><td><b>Hora de Regresso:</b></td><td>' .date('H:i', strtotime($compra->flight_back->datehourdeparture)).'</td></tr>' : '';

$html = '<h2>Obrigador por ter Comprado uma Viagem</h2><br><h3>Descrição da Viagem<br> </h3> '.
'<table>
<tr><td><b>Voo:</b></td><td>'.$compra->flight->flightname.'</td></tr>
<tr><td><b>Data de Compra:</b></td><td>' .date('d/m/Y', strtotime($compra->purchasedate)).'</td></tr>
<tr><td><b>Hora de Compra:</b></td><td>' .date('H:i', strtotime($compra->purchasedate)).'</td></tr>
<tr><td><b>Lugar no Avião:</b></td><td>'.$compra->planeplace.'</td></tr>
<tr><td><b>Preço:</b></td><td>'.$compra->price.'€'.'</td></tr>'
    .$flightback.
'<br><tr><td><b>Estado do Check-in:</b></td><td>'.$checkin.'</td></tr>
</table>
<br><br><p></p><br><h2>Desejamos-lhe uma Boa Viagem</h2>';

//Escrever no pdf o html
$pdf->writeHTML($html, true, false, true, false, '');
// reset pointer to the last page
$pdf->lastPage();
//Close and output PDF document
ob_end_clean();
$pdf->Output('bilhete_'.date("Y-m-d").'.pdf', 'D');
?>
