<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}

$aeroportos = Data::get('airports');
$avioes = Data::get('airplanes');
$voos = Data::get('flights');
//Página quer permite a criação de uma escala e inserção dos dados na base de dados
?>

<div class="cxfloatvooscreate">
    <div class="cardvooscreate">
        <ul class="firstline">
            <li class="textoAdicionarAviao">Adicionar Escalas ao voo <?=$voos->flightname?></li>
            <a href="<?=Url::toRoute('scales/index')?>">
                <li class="veravioes">Ver Escalas</li>
            </a>
        </ul>
        <div class="tabelaPlaceVoos">
            <form class="formulario-todo" action="<?=Url::toRoute('scales/storefromvoo', $voos->flights_id)?>" method="post">

                <input type="text" class="form-control form" name="flightname" title="Insira a o nome da escala" placeholder="Nome da Escala" required>

                <input type="datetime-local" class="form-control form" name="datehourarrival" title="Insira a data e hora de chegada da escala" placeholder="Data e hora de Chegada" required>

                <select class="form-control form" name="airport_id" title="Insira o aeroporto de paragem" required>
                    <option disabled selected>Aeroporto de Paragem</option>
                    <?php foreach ($aeroportos as $dados){ ?>
                        <option value="<?=$dados->airports_id?>"><?=$dados->airportname?></option>
                    <?php } ?>
                </select>

                <select class="form-control form" name="airplane_id" title="Insira o avião" required>
                    <option disabled selected>Avião de Partida</option>
                    <?php foreach ($avioes as $dados){ ?>
                        <option value="<?=$dados->airplanes_id?>"><?=$dados->airplanename?></option>
                    <?php } ?>
                </select>

                <input class="btn botaosignin" type="submit" value="Adicionar">

            </form>
        </div>
        </ul>
    </div>
</div>

<?=Layout::includeLayout('footer')?>