<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}

$escala = Data::get('escala');
?>

    <div class="cxfloatvooscreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Escala</li>
                <a href="<?=Url::toRoute('scales/index')?>">
                    <li class="veravioes">Ver Escalas</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('scales/update', $escala->flight_id)?>" method="post">
                <input type="text" class="form-control form" value="<?=$escala->flightname?>" name="flightname" title="Insira o nome da escala" placeholder="Escala" required>
                <input type="datetime-local" class="form-control form" value="<?=$escala->datehourdeparture?>T<?=$escala[0]->datehourdeparture?>" name="DataHoraPartida" title="Insira a data de partida do voo" placeholder="Data de Partida" required>
                <input type="datetime-local" class="form-control form" value="<?=$escala->datehourarrival?>T<?=$escala[0]->datehourarrival?>" name="DataHoraChegada" title="Insira a data de chegada do voo" placeholder="Data de Chegada" required>
                <input type="text" class="form-control form" value="<?=$escala->originairport_id?>" name="airport_id" title="Insira o aeroporto de paragem" placeholder="Aeroporto de Paragem" required>
                <input type="text" class="form-control form" value="<?=$escala->airplane_id?>" name="airplane_id" title="Insira o avião" placeholder="Avião" required>
                <input type="text" class="form-control form" value="<?=$escala->flight_id?>" name="flight_id" title="Insira o voo" placeholder="Voo" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>