<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
}

?>

<?php
$escalas = Data::get('scales');
$voo = Data::get('voo');
//Página que permite ver todas as escalas registadas na base de dados
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao">Escalas do voo <?=$voo->flightname?></li>

            <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                <a href="<?=Url::toRoute('scales/createfromvoo', $voo->flights_id)?>">
                    <li class="adicionaraviao">Adicionar Escala</li>
                </a>
            <?php }else{ ?>
                <a href="<?=Url::toRoute('flights/index')?>">
                    <li class="adicionaraviao">Voltar</li>
                </a>
            <?php }?>

        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Escala</th>
                    <th scope="col">Data de Chegada</th>
                    <th scope="col">Aeroporto de Paragem</th>
                    <th scope="col">Avião</th>
                    <th scope="col">Voo</th>

                    <!--Tirar a opção ao passageiro de poder alterar os voos-->
                    <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    <?php }?>

                </tr>
                </thead>
                <tbody>
                <?php foreach ($escalas as $dados){ ?>
                    <tr>
                        <td><?=$dados->flightname?></td>
                        <td><?=date('d/m/Y H:i', strtotime($dados->datehourarrival))?></td>
                        <td><?=$dados->airport->airportname?></td>
                        <td><?=$dados->airplane->airplanename?></td>
                        <td><?=$dados->flight->flightname?></td>

                        <!--Tirar a opção ao passageiro de poder alterar os voos-->
                        <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                            <td><a href="<?=Url::toRoute('scales/edit', $dados->scales_id)?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="30"></a></td>
                            <td><a href="<?=Url::toRoute('scales/destroy', $dados->scales_id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                        <?php }?>

                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

