<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}

?>

<?php
$escalas = Data::get('scales');
$voo = Data::get('voo');
//Página que permite ver todas as escalas registadas na base de dados
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao">Escalas do voo <?=$voo->flightname?></li>

            <?php if($_SESSION['tipoUser'] != 'passageiro' && $_SESSION['tipoUser'] != 'operadordecheckin'){ ?>
                <a href="<?=Url::toRoute('scales/createfromvoo', $voo->flights_id)?>">
                    <li class="adicionaraviao">Adicionar Escala</li>
                </a>
            <?php }else{ ?>
                <a href=<?=($_SESSION['tipoUser'] != 'passageiro')?"javascript:history.go(-1)":Url::toRoute('flights/index')?>>
                    <li class="adicionaraviao">Voltar</li>
                </a>
            <?php }?>

        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Escala</th>
                    <th scope="col">Data de Partida</th>
                    <th scope="col">Data de Chegada</th>
                    <th scope="col">Aeroporto de Origem</th>
                    <th scope="col">Aeroporto de Chegada</th>
                    <th scope="col">Avião</th>
                    <th scope="col">Distância</th>

                    <!--Tirar a opção ao passageiro de poder alterar os voos-->
                    <?php if($_SESSION['tipoUser'] != 'passageiro' && $_SESSION['tipoUser'] != 'operadordecheckin'){ ?>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    <?php }elseif ($_SESSION['tipoUser'] == 'operadordecheckin'){?>
                    <?php } ?>

                </tr>
                </thead>
                <tbody>
                <!-- Preenche as escalas na tabela -->
                <?php foreach ($escalas as $dados){ ?>
                    <tr>
                        <td><?=$dados->flightname?></td>
                        <td><?=date('d/m/Y H:i', strtotime($dados->datehourdeparture))?></td>
                        <td><?=date('d/m/Y H:i', strtotime($dados->datehourarrival))?></td>
                        <td><?=$dados->origin_airport->airportname?>
                            <img class="imgbandeiras" src="<?=$dados->origin_airport->flag?>" width="30">
                        </td>
                        <td><?=$dados->destination_airport->airportname?>
                            <img class="imgbandeiras" src="<?=$dados->destination_airport->flag?>" width="30">
                        </td>
                        <td><?=$dados->airplane->airplanename?></td>
                        <td><?=$dados->distance?> km</td>
                        <!--Tirar a opção ao passageiro de poder alterar os voos-->
                        <?php if($_SESSION['tipoUser'] != 'passageiro' && $_SESSION['tipoUser'] != 'operadordecheckin'){ ?>
                            <td><a href="<?=Url::toRoute('scales/edit', $dados->scales_id)?>" title="Editar"><?=imgeditar()?></a></td>
                            <td><a href="<?=Url::toRoute('scales/destroy', $dados->scales_id)?>" title="Apagar"><?=imgapagar()?></a></td>
                        <?php }?>

                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

