<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}

$aeroportos = Data::get('airports');
$avioes = Data::get('airplanes');
// Página que permite criar/registar voos na base de dados
?>

<div class="cxfloatvooscreate">
    <div class="cardvooscreate">
        <ul class="firstline">
            <li class="textoAdicionarAviao">Adicionar Voos</li>
            <a href="<?=Url::toRoute('flights/index')?>">
                <li class="veravioes">Ver Voos</li>
            </a>
        </ul>
        <div class="tabelaPlaceVoos">
            <form class="formulario-todo" action="<?=Url::toRoute('flights/store')?>" method="post">

                <input type="text" class="form-control form" name="flightname" title="Insira o nome do voo" placeholder="Nome do Voo" required>

                <input type="datetime-local" class="form-control form" name="datehourdeparture" title="Insira a data de partida do voo" placeholder="Data de Partida" required>

                <input type="datetime-local" class="form-control form" name="datehourarrival" title="Insira a data de chegada do voo" placeholder="Data de Chegada" required>

                <select class="form-control form" name="origin_airport_id" title="Insira o aeroporto de origem" required>
                    <option disabled selected>Aeroporto de Origem</option>
                    <?php foreach ($aeroportos as $dados){ ?>
                        <option value="<?=$dados->airports_id?>"><?=$dados->airportname?></option>
                    <?php } ?>
                </select>

                <select class="form-control form" name="destination_airport_id" title="Insira o aeroporto de destino" required>
                    <option disabled selected>Aeroporto de Destino</option>
                    <?php foreach ($aeroportos as $dados){ ?>
                        <option value="<?=$dados->airports_id?>"><?=$dados->airportname?></option>
                    <?php } ?>
                </select>

                <select class="form-control form" name="airplane_id" title="Insira o avião" required>
                    <option disabled selected>Avião</option>
                    <?php foreach ($avioes as $dados){ ?>
                        <option value="<?=$dados->airplanes_id?>"><?=$dados->airplanename?></option>
                    <?php } ?>
                </select>

                <input type="number" class="form-control form" name="price" title="Insira o preço do voo" placeholder="Preço da Viajem" required>

                <input class="btn botaosignin" type="submit" value="Adicionar">

            </form>
        </div>
        </ul>
    </div>
</div>

<?=Layout::includeLayout('footer')?>