<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}

$voo = Data::get('voo');
$aeroportos = Data::get('airports');
$avioes = Data::get('airplanes');
//Página que permite a edição de um voo selecionado pelo user
?>

    <div class="cxfloatvooscreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Voo</li>
                <a href="<?=Url::toRoute('flights/index')?>">
                    <li class="veravioes">Ver Voos</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('flights/update', $voo->flights_id)?>" method="post">
                <input type="text" class="form-control form" value="<?=$voo->flightname?>" name="flightname" title="Insira o nome do Voo" placeholder="Voo" required>
                <input type="datetime-local" class="form-control form" value="<?=date('Y-m-d',strtotime($voo->datehourdeparture))?>T<?=date('H:i',strtotime($voo->datehourdeparture))?>" name="datehourdeparture" title="Insira a data de partida do voo" placeholder="Data de Partida" required>
                <input type="datetime-local" class="form-control form" value="<?=date('Y-m-d',strtotime($voo->datehourarrival))?>T<?=date('H:i',strtotime($voo->datehourarrival))?>" name="datehourarrival" title="Insira a data de chegada do voo" placeholder="Data de Chegada" required>
                <select class="form-control form" name="origin_airport_id" title="Insira o aeroporto de origem" required>
                    <option disabled selected>Aeroporto de Origem</option>
                    <?php foreach ($aeroportos as $dados){ ?>
                        <option value="<?=$dados->airports_id?>" <?=($voo->origin_airport->airports_id == $dados->airports_id)?'selected':''?>><?=$dados->airportname?></option>
                    <?php } ?>
                </select>

                <select class="form-control form" name="destination_airport_id" title="Insira o aeroporto de destino" required>
                    <option disabled selected>Aeroporto de Destino</option>
                    <?php foreach ($aeroportos as $dados){ ?>
                        <option value="<?=$dados->airports_id?>" <?=($voo->destination_airport->airports_id == $dados->airports_id)?'selected':''?>><?=$dados->airportname?></option>
                    <?php } ?>
                </select>

                <select class="form-control form" name="airplane_id" title="Insira o avião" required>
                    <option disabled selected>Avião</option>
                    <?php foreach ($avioes as $dados){ ?>
                        <option value="<?=$dados->airplanes_id?>" <?=($voo->airplane->airplanes_id == $dados->airplanes_id)?'selected':''?>><?=$dados->airplanename?></option>
                    <?php } ?>
                </select>

                <input type="text" class="form-control form" value="<?=$voo->price?>" name="price" title="Insira o preço da viagem" placeholder="Preço" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>