<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('header');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('header');
        break;
    default:
        Redirect::toRoute('users/index');
        break;
}

$voos = Data::get('voos');
$searchbar = Data::get('searchbar');

//Página que mostra todos os voos registados na base de dados
?>


<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao"><a href="<?=Url::toRoute('flights/index')?>">Voos</a></li>
            <li>
                <form class="formSearch" method="post" action="<?=Url::toRoute('flights/search')?>">
                    <input type="text" class="form-control form" title="Escreva aqui o que quer procurar" placeholder="Procurar" name="search" value="<?=$searchbar?>" required>
                    <input type="submit" class="btn botaosearch" value="Procurar">
                </form>
            </li>
            <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                <a href="<?=Url::toRoute('flights/create')?>">
                    <li class="adicionaraviao">Adicionar Voo</li>
                </a>
            <?php } ?>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Voo</th>
                    <th scope="col">Data de Partida</th>
                    <th scope="col">Data de Chegada</th>
                    <th scope="col">Aeroporto de Origem</th>
                    <th scope="col">Aeroporto de Chegada</th>
                    <th scope="col">Avião</th>
                    <th scope="col">Preço</th>
                    <th scope="col"></th>
                    <th scope="col"></th>

                    <!--Tirar a opção ao passageiro de poder alterar os voos-->
                    <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                        <th scope="col"></th>
                    <?php } ?>

                </tr>
                </thead>
                <tbody>
                <?php foreach ($voos as $dados){ ?>
                    <tr>
                        <td><?=$dados->flightname?></td>
                        <td><?=date('d/m/Y H:i', strtotime($dados->datehourdeparture))?></td>
                        <td><?=date('d/m/Y H:i', strtotime($dados->datehourarrival))?></td>
                        <td><?=$dados->origin_airport->airportname?></td>
                        <td><?=$dados->destination_airport->airportname?></td>
                        <td><?=$dados->airplane->airplanename?></td>
                        <td><?=$dados->price.'€'?></td>
                        <td><a href="<?=Url::toRoute('scales/show', $dados->flights_id)?>"><img title="Escalas" alt="escalas" src="<?=Asset::image('escala.png')?>"></a></td>x

                        <!--Tirar a opção ao passageiro de poder alterar os voos-->
                        <?php if($_SESSION['tipoUser'] != 'passageiro'){ ?>
                            <td><a href="<?=Url::toRoute('flights/edit', $dados->flights_id)?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="32"></a></td>
                            <td><a href="<?=Url::toRoute('flights/destroy', $dados->flights_id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                        <?php }else{ ?>
                            <td><a href="<?=Url::toRoute('users_flights/index', $dados->flights_id)?>"><img title="Comprar passagem" alt="apagar" src="<?=Asset::image('comprar.png')?>" width="32"></a></td>
                        <?php }?>

                    </tr>
                <?php } ?>
                </tbody>
            </table>

            <!--Mensagem de nenhum voo encontrado-->
            <?=(empty($voos))?'<p class="nenhumVoo">Nenhum voo encontrado</p>':''?>

        </div>

        <!--Mensagem de erro ao tentar eliminar chaves estrangeiras-->
        <?=(isset($_SESSION['mensagemErro']))?'<p class="nenhumVoo">'.$_SESSION['mensagemErro'].'</p>':''?>
        <?php unset($_SESSION['mensagemErro']); ?>

    </div>
</div>

<?=Layout::includeLayout('footer')?>

