<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

?>

<?=Layout::includeLayout('header')?>

<?php $voos = Data::get('voos');
?>

<div class="cxfloatvoos">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao">Voos</li>
            <a href="<?=Url::toRoute('flights/create')?>">
                <li class="adicionaraviao">Adicionar Voo</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Voo</th>
                    <th scope="col">Data de Partida</th>
                    <th scope="col">Data de Chegada</th>
                    <th scope="col">Aeroporto de Origem</th>
                    <th scope="col">Aeroporto de Chegada</th>
                    <th scope="col">Avião</th>
                    <th scope="col">Preço</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($voos as $dados){ ?>
                    <tr>
                        <td><?=$dados->flightname?></td>
                        <td><?=date('d/m/Y H:i', strtotime($dados->datehourdeparture))?></td>
                        <td><?=date('d/m/Y H:i', strtotime($dados->datehourarrival))?></td>
                        <td><?=$dados->origin_airport->airportname?></td>
                        <td><?=$dados->destination_airport->airportname?></td>
                        <td><?=$dados->airplane->airplanename?></td>
                        <td><?=$dados->price.'€'?></td>
                        <td><a href="<?=Url::toRoute('flights/edit', $dados->flights_id)?>"><img title="Editar" alt="editar" src="<?=Asset::image('editar.png')?>" width="30"></a></td>
                        <td><a href="<?=Url::toRoute('flights/destroy', $dados->flights_id)?>"><img title="Apagar" alt="apagar" src="<?=Asset::image('apagar.png')?>" width="32"></a></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>

