<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
}

// Recebe os dados do controller
$paises = Data::get('paises');

// Página que permite criar/registar voos na base de dados
?>

    <div class="cxfloatvoosusersearch">
        <div class="cardvooscreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Pesquisar por voos</li>
            </ul>
            <div class="tabelaPlaceVoos">
                <form class="formulario-todo" action="<?=Url::toRoute('flights/index')?>" method="post">

                    <div class="conteinersearch">

                        <select class="form-control form searchitem" name="origin_airportname" title="Insira o país de origem">
                            <option readonly="true" selected>País de origem</option>
                            <?php foreach ($paises as $pais){
                                if($pais->capital != null){ ?>
                                    <option><?=$pais->name." - ".$pais->capital?></option>
                                <?php }
                            } ?>
                        </select>

                        <select class="form-control form searchitem" name="destination_airportname" title="Insira o país de destino">
                            <option readonly="true" selected>País de destino</option>
                            <?php foreach ($paises as $pais){
                                if($pais->capital != null){ ?>
                                    <option><?=$pais->name." - ".$pais->capital?></option>
                                <?php }
                            } ?>
                        </select>

                    </div>

                    <div class="conteinersearch">

                        <input type="date" id="" class="form-control form searchitem" name="datehourdeparture" title="Indique a data inicial de pesquisa do voo" placeholder="Data inicial de Partida">

                        <input type="date" class="form-control form searchitem" name="datehourdeparturefinal" title="Indique a data final de pesquisa do voo" placeholder="Data final de Partida">

                    </div>
                    <input class="btn botaosignin" type="submit" value="Pesquisar">

                </form>
            </div>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>