<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('loginheader')
// Página de registo de utilizadores
?>

<div style="background-image: url(<?=Asset::image('loginFundo'.rand(1,3).'.jpg')?>);" id="imagemlogin">
    <div class="card2">Aeroporto</div>
    <div class="cxfloatcreate">
        <div class="cardcreate">
            <ul class="firstline">
                <li class="textologin">Criar conta</li>
                <a href="<?=Url::toRoute('users/index')?>">
                    <li class="createaccount">Entrar</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('users/store')?>" method="post">
                <input type="text" class="form-control form" name="username" title="Insira um username" maxlength="100" placeholder="Nome de Utilizador" required>
                <input type="text" class="form-control form" name="fullname" title="Insira o nome completo" placeholder="Nome completo" maxlength="100" required>
                <input type="date" class="form-control form" name="birthdate" title="Insira a sua data de nascimento" placeholder="Data de nascimento" required>
                <input type="email" class="form-control form" name="email" title="Insira o seu email" maxlength="100" placeholder="Email" required>
                <input type="tel" class="form-control form" name="phonenumber" pattern="[0-9]{9}" maxlength="9" title="Insira o seu telefone, 9 digitos sem letras" placeholder="Telefone" required>
                <input type="password" class="form-control form" name="userpassword" title="Insira uma password" maxlength="100" placeholder="Palavra-passe" required>
                <input class="btn botaosignin" type="submit" value="Criar">
            </form>
            </ul>
        </div>
    </div>
</div>