<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('loginheader')
//Página de registo de utilizadores
?>

<div style="background-image: url(<?=Asset::image('loginFundo'.rand(1,3).'.jpg')?>);" id="imagemlogin">
    <div class="cxfloatcreate">
        <div class="cardcreate">
            <ul class="firstline">
                <li class="textologin">Criar conta</li>
                <a href="<?=Url::toRoute('users/index')?>">
                    <li class="createaccount">Login</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('users/store')?>" method="post">
                <input type="text" class="form-control form" name="username" title="Insira um username" placeholder="Username" required>
                <input type="text" class="form-control form" name="fullname" title="Insira o nome completo" placeholder="Nome completo" required>
                <input type="date" class="form-control form" name="birthdate" title="Insira a sua data de nascimento" placeholder="Data de nascimento" required>
                <input type="email" class="form-control form" name="email" title="Insira o seu email" placeholder="Email" required>
                <input type="number" class="form-control form" name="phonenumber" title="Insira o seu telefone" placeholder="Telefone" required>
                <input type="password" class="form-control form" name="userpassword" title="Insira uma password" placeholder="Password" required>
                <input class="btn botaosignin" type="submit" value="Criar">
            </form>
            </ul>
        </div>
    </div>
</div>