<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    case 'passageiro':
        Layout::includeLayout('passageiroheader');
        break;
    case 'gestordevoo':
        Layout::includeLayout('gestordevooheader');
        break;
    case 'operadordecheckin':
        Layout::includeLayout('operadordecheckinheader');
        break;
    default:
        Redirect::toRoute('users/index');
        break;
}

$utilizador = Data::get('utilizador');
//Página que permite a editar os dados de um user escoljhido pelo administrador
?>

    <div class="cxfloatutilizadoredit">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Utilizador</li>

                <?php if($_SESSION['tipoUser'] == 'administrador'){ ?>
                    <a href="<?=Url::toRoute('users/showall')?>">
                        <li class="veravioes">Ver utilizadores</li>
                    </a>
                <?php }else{ ?>
                    <a href="<?=Url::toRoute('flights/index')?>">
                        <li class="veravioes">Voltar</li>
                    </a>
                <?php } ?>

            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('users/update', $utilizador->users_id)?>" method="post">
                <input type="text" class="form-control form" value="<?=$utilizador->fullname?>" maxlength="100" name="fullname" title="Insira o seu nome" placeholder="Nome" required>
                <input type="date" class="form-control form" value="<?=date('Y-m-d',strtotime($utilizador->birthdate))?>" name="birthdate" title="Insira a sua data de nascimento" required>
                <input type="email" class="form-control form" value="<?=$utilizador->email?>" name="email" title="Insira o seu email" placeholder="email" required>
                <input type="tel" class="form-control form" value="<?=$utilizador->phonenumber?>" pattern="[0-9]{9}" maxlength="9" title="Insira o seu telefone, 9 digitos sem letras" name="phonenumber" title="Insira o seu telefone" placeholder="Telefone" required>
                <input type="text" class="form-control form" value="<?=$utilizador->username?>" name="username" title="Insira o seu nome de utilizador" placeholder="Username" required>
                <input type="password" class="form-control form" value="<?=$utilizador->userpassword?>" name="userpassword" title="Insira a sua password" placeholder="Password" required>
                <?php if($_SESSION['tipoUser'] == 'administrador'){ ?>
                    <select class="form-control form" name="userprofile" title="Indique o tipo de perfil">
                        <option value="administrador" <?=($utilizador->userprofile == "administrador")?'selected':''?>>Administrador</option>
                        <option value="gestordevoo" <?=($utilizador->userprofile == "gestordevoo")?'selected':''?>>Gestor de Voo</option>
                        <option value="operadordecheckin" <?=($utilizador->userprofile == "operadordecheckin")?'selected':''?>>Operador de Checkin</option>
                        <option value="passageiro" <?=($utilizador->userprofile == "passageiro")?'selected':''?>>Passageiro</option>
                    </select>
                <?php } ?>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>