<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('loginheader')
//Página de login de utilizadores
?>

<div style="background-image: url(<?=Asset::image('loginFundo'.rand(1,3).'.jpg')?>);" id="imagemlogin">
    <div class="cxfloat">
        <div class="card">
            <ul class="firstline">
                <li class="textologin">LOGIN</li>
                <a href="<?=Url::toRoute('users/create')?>">
                    <li class="createaccount">Criar conta</li>
                </a>
            </ul>
            <form class="formulario-todo" method="post" action="<?=Url::toRoute('users/login', "logged")?>">
                <input type="text" class="form-control form" name="username" title= "Insira um username" placeholder="Username" required>
                <input type="password" class="form-control form" name="userpassword" title="Insira uma password" placeholder="Password" required>
                <span id="mensagem"><?=(isset($_SERVER['mensagem']))?$_SERVER['mensagem']:""?></span>
                <input class="btn botaosignin" type="submit" value="Entrar">
            </form>

            <ul class="Secondline">
                <a href="#">
                <li class="forgotpass">Esqueceu a sua password?</li>
                </a>
            </ul>
        </div>
    </div>
</div>