<?php
/**
 * Created by PhpStorm.
 * User: smendes
 * Date: 19-04-2017
 * Time: 18:57
 */

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\URL;

switch ($_SESSION['tipoUser']) {
    //Mostrar o header conforme o tipo de utilizador
    //Redirecionar os users que não são administradores para o login
    case 'administrador':
        Layout::includeLayout('adminheader');
        break;
    default:
        Redirect::toRoute('users/index');
        break;
}
?>

<?php
$utilizadores = Data::get('users');
$searchbar = Data::get('searchbar');
$user = new User();

//Página que permite ver todos os users registados na base de dados
//Disponivel apenas para users administradores
?>

<div class="cxfloatshowall">
    <div class="cardavioes">
        <ul class="firstline">
            <li class="textoAviao"><a href="<?=Url::toRoute('users/showall')?>">Utilizadores</a></li>
            <li>
                <form class="formSearch" method="post" action="<?=Url::toRoute('users/search')?>">
                    <input type="text" class="form-control form" title="Escreva aqui o que quer procurar" placeholder="Procurar" name="search" value="<?=$searchbar?>" required>
                    <input type="submit" class="btn botaosearch" value="Procurar">
                </form>
            </li>
            <a href="<?=Url::toRoute('users/create')?>">
                <li class="adicionaraviao">Adicionar Utilizador</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Data de nascimento</th>
                    <th scope="col">Email</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Utilizador</th>
                    <th scope="col">Perfil</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($utilizadores as $dados){ ?>
                    <tr>
                        <td><?=$dados->fullname?></td>
                        <td><?=date('d/m/Y', strtotime($dados->birthdate))?></td>
                        <td><?=$dados->email?></td>
                        <td><?=$dados->phonenumber?></td>
                        <td><?=$dados->username?></td>
                        <td><?=$user->TipoUserMostrar($dados->userprofile)?></td>
                        <td><a title="Editar" href="<?=Url::toRoute('users/edit', $dados->users_id)?>"><?=imgcheckin()?></a></td>
                        <?php if($dados->userprofile != 'administrador'){ ?>
                            <td><a title="Apagar" href="<?=Url::toRoute('users/destroy', $dados->users_id)?>"><?=imgapagar()?></a></td>
                        <?php } ?>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <?=(empty($utilizadores))?'<p class="nenhumVoo">Nenhum utilizador encontrado</p>':''?>
        </div>
    </div>
</div>

<?=Layout::includeLayout('footer')?>