<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('header');

$aeroportos = Data::get('aeroportos');
$avioes = Data::get('avioes');
?>

<div class="cxfloatvooscreate">
    <div class="cardavioescreate">
        <ul class="firstline">
            <li class="textoAdicionarAviao">Adicionar Voos</li>
            <a href="<?=Url::toRoute('voos/index')?>">
                <li class="veravioes">Ver Voos</li>
            </a>
        </ul>
        <div class="tabelaPlace">
            <form class="formulario-todo" action="<?=Url::toRoute('voos/store')?>" method="post">

                <input type="text" class="form-control form" name="NomeVoo" title="Insira o nome do voo" placeholder="Nome do Voo" required>

                <input type="datetime-local" class="form-control form" name="DataHoraPartida" title="Insira a data de partida do voo" placeholder="Data de Partida" required>

                <input type="datetime-local" class="form-control form" name="DataHoraChegada" title="Insira a data de chegada do voo" placeholder="Data de Chegada" required>

                <select class="form-control form" name="IdAeroportoOrigem" title="Insira o aeroporto de origem" required>
                    <option disabled selected>Aeroporto de Origem</option>
                    <?php foreach ($aeroportos as $dados){ ?>
                        <option value="<?=$dados->idaeroporto?>"><?=$dados->nomeaeroporto?></option>
                    <?php } ?>
                </select>

                <select class="form-control form" name="IdAeroportoDestino" title="Insira o aeroporto de destino" required>
                    <option disabled selected>Aeroporto de Destino</option>
                    <?php foreach ($aeroportos as $dados){ ?>
                        <option value="<?=$dados->idaeroporto?>"><?=$dados->nomeaeroporto?></option>
                    <?php } ?>
                </select>

                <select class="form-control form" name="IdAviao" title="Insira o avião" required>
                    <option disabled selected>Avião</option>
                    <?php foreach ($avioes as $dados){ ?>
                        <option value="<?=$dados->idaviao?>"><?=$dados->nomeaviao?></option>
                    <?php } ?>
                </select>

                <input type="text" class="form-control form" name="Preco" title="Insira o preço do voo" placeholder="Preço da Viajem" required>

                <input class="btn botaosignin" type="submit" value="Adicionar">

            </form>
        </div>
        </ul>
    </div>
</div>

<?=Layout::includeLayout('footer')?>