<?php use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;


Layout::includeLayout('header');

$voo = Data::get('voo');
?>

    <div class="cxfloatavioescreate">
        <div class="cardavioescreate">
            <ul class="firstline">
                <li class="textoAdicionarAviao">Alterar Voo</li>
                <a href="<?=Url::toRoute('voos/index')?>">
                    <li class="veravioes">Ver Voos</li>
                </a>
            </ul>
            <form class="formulario-todo" action="<?=Url::toRoute('voos/update', $voo[0]->idvoo)?>" method="post">
                <input type="date" class="form-control form" value="<?=$voo[0]->datahorapartida?>" name="DataHoraPartida" title="Insira a data de partida do voo" placeholder="Data de Partida" required>
                <input type="date" class="form-control form" value="<?=$voo[0]->datahorachegada?>" name="DataHoraChegada" title="Insira a data de chegada do voo" placeholder="Data de Chegada" required>
                <input type="text" class="form-control form" value="<?=$voo[0]->idaeroportoorigem?>" name="IdAeroportoOrigem" title="Insira o aeroporto de origem" placeholder="Aeroporto de Origem" required>
                <input type="text" class="form-control form" value="<?=$voo[0]->idaeroportodestino?>" name="IdAeroportoDestino" title="Insira o aeroporto de destino" placeholder="Aeroporto de Destino" required>
                <input type="text" class="form-control form" value="<?=$voo[0]->idaviao?>" name="IdAviao" title="Insira o avião" placeholder="Avião" required>
                <input class="btn botaosignin" type="submit" value="Alterar">
            </form>
            </ul>
        </div>
    </div>

<?=Layout::includeLayout('footer')?>